repository: ajlee/ajlee.github.io
url: "ajlee.github.io" # the base hostname & protocol for your site, e.g. http://example.acom
baseurl: "" # the subpath of your site, e.g. /blog
header_title: "Alex Lee Websites" # the name of your site, e.g. ACME Corp.
header_subtitle: "Cheap, Simple Websites"
seo_description: "This is my meta seo_description"
colour_scheme: ""
font_scheme: ""
one_page_site: "" # disables nav
sass:
  sass_dir: _sass
  style: compressed        # optional, but common
  quiet_deps: true         # suppresses Pico.css dependency warnings
collections:
  pages:
    output: true
    permalink: /:name          # results in /test/ (trailing slash) or use /:name for /test
    source: _pages              # where your markdown files live
defaults:
  - scope:
      path: "_pages"
    values:
      layout: default   # your existing layout file