seo_info:
  title: Alex Lee Websites
  seo_description: 'Cheap, simple websites'
  seo_siteowner: Alex Lee
  seo_logo: ''
nav:
  - title: Home
    link: /
  - title: About
    link: /about
  - title: Contact
    link: /contact
contactLinks:
  - title: Email
    link: /contact
    icon: 'icon-email'
  - title: Mastodon
    link: 'https://science.social/alexlee'
    icon: brand-mastodon
  - title: Github
    link: 'https://github.com/ajlee'
    icon: 'brand-github'
footerStarfield: true
