seo:
  title: Alex Lee Websites
  description: 'Cheap, simple websites'
  siteOwner: Alex Lee
  logo: ''
nav:
  - title: Home
    link: /
  - title: About
    link: /about
  - title: Contact
    link: /contact
contactLinks:
  - title: Contact
    link: /contact
    icon: 'tabler:icon-email'
  - title: Mastodon
    link: 'https://social.science/'
    icon: brand-x
  - title: Github
    link: 'https://github.com'
    icon: 'tabler:brand-github'
footerStarfield: true
